export { default as AboutPage } from './AboutPage'
export { default as WithoutSideBar } from './WithoutSideBar'
export { default as IncomingPage } from './IncomingPage'
export { default as StructurePage } from './StructurePage'
export { default as DepartmentsPage } from './DepartmentsPage'
export { default as TrainingUnitsPage } from './TrainingUnitsPage'
export { default as DraftPage } from './DraftPage'
